update the install scripts

diff --git a/seafile_ubuntu b/seafile_ubuntu
--- a/seafile_ubuntu
+++ b/seafile_ubuntu
@@ -31,7 +31,7 @@ set -e
 
 if [[ "$#" -ne 1 ]]; then
     echo "You must specif Seafile version to install"
-    echo "Like: $0 4.4.2"
+    echo "Like: $0 7.0.0"
     exit 1
 fi
 
@@ -114,11 +114,11 @@ if is_pro; then
         echo
         exit 1
     fi
-    INSTALLPATH=/opt/seafile/seafile-pro-server-${SEAFILE_VERSION}/
+    INSTALLPATH=${SEAFILE_SERVER_HOME}/seafile-pro-server-${SEAFILE_VERSION}/
 else
     SEAFILE_SERVER_PACKAGE=seafile-server_${SEAFILE_VERSION}_x86-64.tar.gz
     SEAFILE_SERVER_PACKAGE_URL=https://download.seadrive.org/${SEAFILE_SERVER_PACKAGE}
-    INSTALLPATH=/opt/seafile/seafile-server-${SEAFILE_VERSION}/
+    INSTALLPATH=${SEAFILE_SERVER_HOME}/seafile-server-${SEAFILE_VERSION}/
 fi
 
 
@@ -131,11 +131,11 @@ fi
 
 
 # -------------------------------------------
-# Abort if directory /opt/seafile/ exists
+# Abort if directory SEAFILE_SERVER_HOME exists
 # -------------------------------------------
-if [[ -d "/opt/seafile/" ]] ;
+if [[ -d "${SEAFILE_SERVER_HOME}" ]] ;
 then
-  echo "  Aborting because directory /opt/seafile/ already exist" ; exit 1
+  echo "  Aborting because directory ${SEAFILE_SERVER_HOME} already exist" ; exit 1
 fi
 
 # -------------------------------------------
@@ -151,80 +151,90 @@ fi
 # Additional requirements
 # -------------------------------------------
 apt-get update
-apt-get install -y python2.7 sudo python-pip python-setuptools python-mysqldb python-ldap python-urllib3 \
-openjdk-8-jre memcached libmemcached-dev zlib1g-dev pwgen curl openssl poppler-utils libpython2.7 libreoffice \
-libreoffice-script-provider-python ttf-wqy-microhei ttf-wqy-zenhei xfonts-wqy nginx python-requests
 
-pip install pylibmc==1.6.0 django-pylibmc==0.6.1
-pip install --timeout=3600 Pillow==4.3.0
-pip install psd-tools==1.4
+if [[ ${SEAFILE_VERSION} =~ 6\.[0-9]*\.[0-9]* ]]; then
+    apt-get install -y python2.7 sudo python-pip python-setuptools python-mysqldb python-ldap python-urllib3 \
+    openjdk-8-jre memcached libmemcached-dev zlib1g-dev pwgen curl openssl poppler-utils libpython2.7 libreoffice \
+    libreoffice-script-provider-python ttf-wqy-microhei ttf-wqy-zenhei xfonts-wqy nginx python-requests
+
+    pip install pylibmc==1.6.0 django-pylibmc==0.6.1
+    pip install --timeout=3600 Pillow==4.3.0
+    pip install psd-tools==1.4
+else
+    apt-get install -y python2.7 sudo python-setuptools python-mysqldb python-ldap python-urllib3 \
+    openjdk-8-jre memcached libmemcached-dev zlib1g-dev pwgen curl openssl poppler-utils libpython2.7 libreoffice \
+    libreoffice-script-provider-python ttf-wqy-microhei ttf-wqy-zenhei xfonts-wqy nginx
+fi
 
 # -------------------------------------------
 # Setup Nginx
 # -------------------------------------------
 
 rm /etc/nginx/sites-enabled/*
-cat > /etc/nginx/sites-available/seafile.conf <<'EOF'
+
+cat > /etc/nginx/sites-available/seafile.conf << EOF
+log_format seafileformat '$http_x_forwarded_for $remote_addr [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $upstream_response_time';
+
 server {
-  listen       80;
-  server_name  "";
-  
-  proxy_set_header X-Forwarded-For $remote_addr;
+    listen 80;
+    server_name seafile.example.com;
 
-  location / {
-    proxy_pass         http://127.0.0.1:8000;
-    proxy_set_header   Host $host;
-    proxy_set_header   X-Real-IP $remote_addr;
-    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
-    proxy_set_header   X-Forwarded-Host $server_name;
-    proxy_set_header   X-Forwarded-Proto $scheme;
-    proxy_read_timeout  1200s;
+    proxy_set_header X-Forwarded-For \$remote_addr;
 
-    # used for view/edit office file via Office Online Server
-    client_max_body_size 0;
+    location / {
+         proxy_pass         http://127.0.0.1:8000;
+         proxy_set_header   Host \$host;
+         proxy_set_header   X-Real-IP \$remote_addr;
+         proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
+         proxy_set_header   X-Forwarded-Host \$server_name;
+         proxy_set_header   X-Forwarded-Proto \$scheme;
+         proxy_read_timeout  1200s;
 
-    access_log      /var/log/nginx/seahub.access.log;
-    error_log       /var/log/nginx/seahub.error.log;
-  }
+         # used for view/edit office file via Office Online Server
+         client_max_body_size 0;
 
-  location /seafhttp {
-    rewrite ^/seafhttp(.*)$ $1 break;
-    proxy_pass http://127.0.0.1:8082;
-    client_max_body_size 0;
-    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
-    proxy_connect_timeout  36000s;
-    proxy_read_timeout  36000s;
-    proxy_send_timeout  36000s;
-    proxy_request_buffering    off;
-  }
+         access_log      /var/log/nginx/seahub.access.log seafileformat;
+         error_log       /var/log/nginx/seahub.error.log;
+    }
+    
+    location /seafhttp {
+         rewrite ^/seafhttp(.*)$ \$1 break;
+         proxy_pass http://127.0.0.1:8082;
+         client_max_body_size 0;
+         proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
+         proxy_connect_timeout  36000s;
+         proxy_read_timeout  36000s;
+         proxy_request_buffering    off;
 
-  location /media {
-    root /opt/seafile/seafile-server-latest/seahub;
-  }
+        access_log      /var/log/nginx/seafhttp.access.log seafileformat;
+        error_log       /var/log/nginx/seafhttp.error.log;
+    }
+    location /media {
+        root ${SEAFILE_SERVER_HOME}/seafile-server-latest/seahub;
+    }
+    location /seafdav {
+        fastcgi_pass    127.0.0.1:8080;
+        fastcgi_param   SCRIPT_FILENAME     \$document_root\$fastcgi_script_name;
+        fastcgi_param   PATH_INFO           \$fastcgi_script_name;
+        fastcgi_param   SERVER_PROTOCOL     \$server_protocol;
+        fastcgi_param   QUERY_STRING        \$query_string;
+        fastcgi_param   REQUEST_METHOD      \$request_method;
+        fastcgi_param   CONTENT_TYPE        \$content_type;
+        fastcgi_param   CONTENT_LENGTH      \$content_length;
+        fastcgi_param   SERVER_ADDR         \$server_addr;
+        fastcgi_param   SERVER_PORT         \$server_port;
+        fastcgi_param   SERVER_NAME         \$server_name;
+        fastcgi_param   REMOTE_ADDR         \$remote_addr;
 
-  location /seafdav {
-    fastcgi_pass    127.0.0.1:8080;
-    fastcgi_param   SCRIPT_FILENAME     $document_root$fastcgi_script_name;
-    fastcgi_param   PATH_INFO           $fastcgi_script_name;
-    fastcgi_param   SERVER_PROTOCOL     $server_protocol;
-    fastcgi_param   QUERY_STRING        $query_string;
-    fastcgi_param   REQUEST_METHOD      $request_method;
-    fastcgi_param   CONTENT_TYPE        $content_type;
-    fastcgi_param   CONTENT_LENGTH      $content_length;
-    fastcgi_param   SERVER_ADDR         $server_addr;
-    fastcgi_param   SERVER_PORT         $server_port;
-    fastcgi_param   SERVER_NAME         $server_name;
-    fastcgi_param   REMOTE_ADDR         $remote_addr;
-  
-    client_max_body_size 0;
-    access_log      /var/log/nginx/seafdav.access.log;
-    error_log       /var/log/nginx/seafdav.error.log;
-  }
+        client_max_body_size 0;
+
+        access_log      /var/log/nginx/seafdav.access.log seafileformat;
+        error_log       /var/log/nginx/seafdav.error.log;
+    }
 }
 EOF
 
 ln -sf /etc/nginx/sites-available/seafile.conf /etc/nginx/sites-enabled/seafile.conf
-
 
 service nginx restart
 
@@ -252,16 +262,15 @@ EOF
   chmod 600 /root/.my.cnf
 fi
 
-
 # -------------------------------------------
 # Seafile init script
 # -------------------------------------------
-cat > /etc/init.d/seafile-server <<'EOF'
+cat > /etc/init.d/seafile-server << EOF
 #!/bin/bash
 ### BEGIN INIT INFO
 # Provides:          seafile-server
-# Required-Start:    $remote_fs $syslog mysql
-# Required-Stop:     $remote_fs $syslog
+# Required-Start:    \$remote_fs \$syslog mysql
+# Required-Stop:     \$remote_fs \$syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: Seafile server
@@ -270,24 +279,26 @@ cat > /etc/init.d/seafile-server <<'EOF'
 
 # Author: Zheng Xie <xie.zheng@seafile.com>
 
-user=seafile
-seafile_dir=/opt/seafile
-script_path=${seafile_dir}/seafile-server-latest
-seafile_init_log=${seafile_dir}/logs/seafile.init.log
-seahub_init_log=${seafile_dir}/logs/seahub.init.log
+# Change the value of "seafile_dir" to your path of seafile installation
+user=${SEAFILE_SERVER_USER}
+seafile_dir=${SEAFILE_SERVER_HOME}
+script_path=\${seafile_dir}/seafile-server-latest
+seafile_init_log=\${seafile_dir}/logs/seafile.init.log
+seahub_init_log=\${seafile_dir}/logs/seahub.init.log
 
-case "$1" in
+
+case "\$1" in
         start)
-                sudo -u ${user} ${script_path}/seafile.sh start >> ${seafile_init_log}
-                sudo -u ${user} ${script_path}/seahub.sh start >> ${seahub_init_log}
+                sudo -u \${user} \${script_path}/seafile.sh start >> \${seafile_init_log}
+                sudo -u \${user} \${script_path}/seahub.sh start >> \${seahub_init_log}
         ;;
         restart)
-                sudo -u ${user} ${script_path}/seafile.sh restart >> ${seafile_init_log}
-                sudo -u ${user} ${script_path}/seahub.sh restart >> ${seahub_init_log}
+                sudo -u \${user} \${script_path}/seafile.sh restart >> \${seafile_init_log}
+                sudo -u \${user} \${script_path}/seahub.sh restart >> \${seahub_init_log}
         ;;
         stop)
-                sudo -u ${user} ${script_path}/seafile.sh $1 >> ${seafile_init_log}
-                sudo -u ${user} ${script_path}/seahub.sh $1 >> ${seahub_init_log}
+                sudo -u \${user} \${script_path}/seafile.sh \$1 >> \${seafile_init_log}
+                sudo -u \${user} \${script_path}/seahub.sh \$1 >> \${seahub_init_log}
         ;;
         *)
                 echo "Usage: /etc/init.d/seafile-server {start|stop|restart}"
@@ -303,8 +314,8 @@ update-rc.d seafile-server defaults
 # -------------------------------------------
 # Seafile
 # -------------------------------------------
-mkdir -p /opt/seafile/installed
-cd /opt/seafile/
+mkdir -p ${SEAFILE_SERVER_HOME}/installed
+cd ${SEAFILE_SERVER_HOME}
 if ! is_pro && [[ ! -e /opt/${SEAFILE_SERVER_PACKAGE} ]]; then
     curl -OL ${SEAFILE_SERVER_PACKAGE_URL}
 else
@@ -360,9 +371,6 @@ mkdir -p ${DEFAULT_CONF_DIR}
 
 ./setup-seafile-mysql.sh auto -u seafile -w ${SQLSEAFILEPW} -r ${SQLROOTPW}
 
-# Fix service url
-eval "sed -i 's/^SERVICE_URL.*/SERVICE_URL = http:\/\/${IP_OR_DOMAIN}/' ${DEFAULT_CONF_DIR}/ccnet.conf"
-
 # -------------------------------------------
 # Configure Seafile WebDAV Server(SeafDAV)
 # -------------------------------------------
@@ -378,9 +386,13 @@ cat >> ${DEST_SETTINGS_PY} <<EOF
 CACHES = {
     'default': {
         'BACKEND': 'django_pylibmc.memcached.PyLibMCCache',
-    'LOCATION': '127.0.0.1:11211',
-    }
+        'LOCATION': '127.0.0.1:11211',
+    },
+    'locmem': {
+        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
+    },
 }
+COMPRESS_CACHE_BACKEND = 'locmem'
 
 # EMAIL_USE_TLS                       = False
 # EMAIL_HOST                          = 'localhost'
@@ -427,7 +439,7 @@ eval "sed -i 's/= ask_admin_password()/= \"${SEAFILE_ADMIN_PW}\"/' ${INSTALLPATH
 # -------------------------------------------
 ${INSTALLPATH}/seafile.sh start
 ${INSTALLPATH}/seahub.sh start
-sleep 2
+sleep 2                         # sleep for a while, otherwise seahub will not be stopped
 ${INSTALLPATH}/seahub.sh stop
 sleep 1
 ${INSTALLPATH}/seafile.sh stop
@@ -447,6 +459,9 @@ fi
 # Fix permissions
 # -------------------------------------------
 chown ${SEAFILE_SERVER_USER}:${SEAFILE_SERVER_USER} -R ${SEAFILE_SERVER_HOME}
+if [[ -d /tmp/seafile-office-output/ ]]; then
+    chown ${SEAFILE_SERVER_USER}:${SEAFILE_SERVER_USER} -R /tmp/seafile-office-output/
+fi
 
 # -------------------------------------------
 # Start seafile server
