Fix path issues

diff --git a/unified/seafile_debian b/unified/seafile_debian
--- a/unified/seafile_debian
+++ b/unified/seafile_debian
@@ -49,7 +49,7 @@ HOSTNAME=$(hostname -f)
 SEAFILE_ADMIN=admin@${HOSTNAME}
 SEAFILE_USER=seafile
 SEAFILE_FILESERVER_PORT=8082
-SEAFILE_SERVER_HOME=/opt/seafile
+SEAFILE_SERVER_HOME=/opt/seafile/
 SEAFILE_TIME_ZONE="Europe/Berlin"
 
 # Don't touch the following variable, unless you know what you are doing
@@ -76,7 +76,6 @@ if [ ${SEAFILE_PRO} = "enabled" ]
     # Seafile Professional
     SEAFILE_SERVER_SOURCE=$(find /usr/src/seafile/seafile-pro-server_*_x86-64.tar.gz | sort -r | head -1)
     SEAFILE_SERVER_VERSION=$(echo ${SEAFILE_SERVER_SOURCE} | awk -F '_' '{ print $2}')
-    SEAFILE_SERVER_INSTALL_PATH=/opt/seafile/seafile-pro-server-${SEAFILE_VERSION}
 fi
 
 
@@ -217,9 +216,9 @@ fi
 
 
 function does-directory-exist-abort-if-it-does {
-if [[ -d "/opt/seafile/" ]] ;
+if [[ -d "${SEAFILE_SERVER_HOME}" ]] ;
 then
-  echo "Aborting because directory /opt/seafile/ already exist" ; exit 1
+  echo "Aborting because directory ${SEAFILE_SERVER_HOME} already exist" ; exit 1
 fi
 }
 
@@ -240,6 +239,11 @@ if [ ${SEAFILE_PRO} = "enabled" ]
 function update-operating-system {
 apt-get update
 apt-get dist-upgrade -y
+}
+
+
+function install-system-utils {
+apt-get install apt-utils -y
 }
 
 
@@ -375,7 +379,7 @@ server {
   }
 
   location /media {
-    root /opt/seafile/seafile-server-latest/seahub;
+    root ${SEAFILE_SERVER_HOME}/seafile-server-latest/seahub;
   }
 
   location /seafdav {
@@ -610,8 +614,8 @@ After=network.target mysql.service
 
 [Service]
 Type=oneshot
-ExecStart=/opt/seafile/seafile-server-latest/seafile.sh start
-ExecStop=/opt/seafile/seafile-server-latest/seafile.sh stop
+ExecStart=${SEAFILE_SERVER_HOME}/seafile-server-latest/seafile.sh start
+ExecStop=${SEAFILE_SERVER_HOME}/seafile-server-latest/seafile.sh stop
 RemainAfterExit=yes
 User=seafile
 Group=nogroup
@@ -626,8 +630,8 @@ Description=Seafile Seahub
 After=network.target seafile.service
 
 [Service]
-ExecStart=/opt/seafile/seafile-server-latest/seahub.sh start-fastcgi 8000
-ExecStop=/opt/seafile/seafile-server-latest/seahub.sh stop
+ExecStart=${SEAFILE_SERVER_HOME}/seafile-server-latest/seahub.sh start-fastcgi 8000
+ExecStop=${SEAFILE_SERVER_HOME}/seafile-server-latest/seahub.sh stop
 User=seafile
 Group=nogroup
 Type=oneshot
@@ -654,41 +658,42 @@ fi
 
 
 function add-system-user {
-adduser --system --gecos "${SEAFILE_USER}" ${SEAFILE_USER} --home /opt/seafile
+adduser --system --gecos "${SEAFILE_USER}" ${SEAFILE_USER} --home ${SEAFILE_SERVER_HOME}
 }
 
 
 function create-seafile-server-directory {
-mkdir -p /opt/seafile/installed
+mkdir -p ${SEAFILE_SERVER_HOME}/installed
 }
 
 
 function get-seafile-sources {
-cd /opt/seafile/
+cd ${SEAFILE_SERVER_HOME}
 if [ ${SEAFILE_PRO} = "enabled" ]
   then
-    cp ${SEAFILE_SERVER_SOURCE} ./seafile-pro-server_${SEAFILE_SERVER_VERSION}_x86-64.tar.gz
-    tar xzf ./seafile-pro-server_${SEAFILE_SERVER_VERSION}_x86-64.tar.gz
-    mv ./seafile-pro-server_${SEAFILE_SERVER_VERSION}_x86-64.tar.gz installed/seafile-pro-server_${SEAFILE_SERVER_VERSION}_x86-64.tar.gz
+    cp ${SEAFILE_SERVER_SOURCE} ${SEAFILE_SERVER_HOME}/seafile-pro-server_${SEAFILE_SERVER_VERSION}_x86-64.tar.gz
+    tar xzf ${SEAFILE_SERVER_HOME}/seafile-pro-server_${SEAFILE_SERVER_VERSION}_x86-64.tar.gz
+    mv ${SEAFILE_SERVER_HOME}/seafile-pro-server_${SEAFILE_SERVER_VERSION}_x86-64.tar.gz ${SEAFILE_SERVER_HOME}/installed/seafile-pro-server_${SEAFILE_SERVER_VERSION}_x86-64.tar.gz
+    SEAFILE_SERVER_INSTALL_PATH=${SEAFILE_SERVER_HOME}/seafile-pro-server-${SEAFILE_SERVER_VERSION}/
   else
     curl -OL https://download.seafile.de/seafile-server_latest_${ARCH}.tar.gz
     tar xzf seafile-server_latest_${ARCH}.tar.gz
-    SEAFILE_SERVER_VERSION=$(basename /opt/seafile/seafile-server-* | awk -F'-' ' { print $3 }')
+    SEAFILE_SERVER_VERSION=$(basename ${SEAFILE_SERVER_HOME}/seafile-server-* | awk -F'-' ' { print $3 }')
     mv seafile-server_latest_${ARCH}.tar.gz installed/seafile-server_${SEAFILE_SERVER_VERSION}_${ARCH}.tar.gz
-    SEAFILE_SERVER_INSTALL_PATH=/opt/seafile/seafile-server-${SEAFILE_SERVER_VERSION}
+    SEAFILE_SERVER_INSTALL_PATH=${SEAFILE_SERVER_HOME}/seafile-server-${SEAFILE_SERVER_VERSION}/
 fi
 }
 
 
 function create-seafile-database {
 SQLSEAFILEPW=$(pwgen 14 1)
-cat > /opt/seafile/.my.cnf <<EOF
+cat > ${SEAFILE_SERVER_HOME}.my.cnf <<EOF
 [client]
 user=seafile
 password=$SQLSEAFILEPW
 EOF
-chmod 600 /opt/seafile/.my.cnf
-chown -R ${SEAFILE_USER}.nogroup /opt/seafile/
+chmod 600 ${SEAFILE_SERVER_HOME}.my.cnf
+chown -R ${SEAFILE_USER}.nogroup ${SEAFILE_SERVER_HOME}
 mysql -e "CREATE DATABASE IF NOT EXISTS \`ccnet-db\` character set = 'utf8';"
 mysql -e "CREATE DATABASE IF NOT EXISTS \`seafile-db\` character set = 'utf8';"
 mysql -e "CREATE DATABASE IF NOT EXISTS \`seahub-db\` character set = 'utf8';"
@@ -784,7 +789,7 @@ if [ ${SEAFILE_PRO} = "enabled" ]
 fi
 
 # Configuring ccnet.conf
-SEAFILE_DB_PW=$(grep password /opt/seafile/.my.cnf | awk -F'=' {'print $2'})
+SEAFILE_DB_PW=$(grep password ${SEAFILE_SERVER_HOME}.my.cnf | awk -F'=' {'print $2'})
 cat >> ${DEFAULT_CCNET_CONF_DIR}/ccnet.conf <<EOF
 
 [Database]
@@ -877,17 +882,17 @@ eval "sed -i 's/= ask_admin_email()/= \"${SEAFILE_ADMIN}\"/' ${SEAFILE_SERVER_IN
 eval "sed -i 's/= ask_admin_password()/= \"${SEAFILE_ADMIN_PW}\"/' ${SEAFILE_SERVER_INSTALL_PATH}/check_init_admin.py"
 
 # Start and stop Seafile eco system. This generates the initial admin user.
-${TOPDIR}/${SEAFILE_SERVER_INSTALL_PATH}/seafile.sh start
-${TOPDIR}/${SEAFILE_SERVER_INSTALL_PATH}/seahub.sh start
-${TOPDIR}/${SEAFILE_SERVER_INSTALL_PATH}/seahub.sh stop
-${TOPDIR}/${SEAFILE_SERVER_INSTALL_PATH}/seafile.sh stop
+${SEAFILE_SERVER_INSTALL_PATH}/seafile.sh start
+${SEAFILE_SERVER_INSTALL_PATH}/seahub.sh start
+${SEAFILE_SERVER_INSTALL_PATH}/seahub.sh stop
+${SEAFILE_SERVER_INSTALL_PATH}/seafile.sh stop
 
 
 # Restore original check_init_admin.py
 mv ${SEAFILE_SERVER_INSTALL_PATH}/check_init_admin.py.backup ${SEAFILE_SERVER_INSTALL_PATH}/check_init_admin.py
 
 # Fix permissions
-chown ${SEAFILE_USER}.nogroup -R /opt/seafile/
+chown ${SEAFILE_USER}.nogroup -R ${SEAFILE_SERVER_HOME}
 
 # Enable office preview in Seahub
 if [ ${SEAFILE_PRO} = "enabled" ]
@@ -900,7 +905,7 @@ fi
 function setup-seafile-server-logrotate {
 apt-get install logrotate -y
 cat > /etc/logrotate.d/seafile <<EOF
-/opt/seafile/logs/seaf-server.log
+${SEAFILE_SERVER_HOME}logs/seaf-server.log
 {
   daily
   missingok
@@ -910,11 +915,11 @@ cat > /etc/logrotate.d/seafile <<EOF
   notifempty
   sharedscripts
   postrotate
-    [ ! -f /opt/seafile/pids/seaf-server.pid ] || kill -USR1 ${cat /opt/seafile/pids/seaf-server.pid}
+    [ ! -f ${SEAFILE_SERVER_HOME}pids/seaf-server.pid ] || kill -USR1 ${cat ${SEAFILE_SERVER_HOME}pids/seaf-server.pid}
   endscript
 }
 
-/opt/seafile/logs/ccnet.log
+${SEAFILE_SERVER_HOME}logs/ccnet.log
 {
   daily
   missingok
@@ -924,7 +929,7 @@ cat > /etc/logrotate.d/seafile <<EOF
   notifempty
   sharedscripts
   postrotate
-    [ ! -f /opt/seafile/pids/ccnet.pid ] || kill -USR1 ${cat /opt/seafile/pids/ccnet.pid}
+    [ ! -f ${SEAFILE_SERVER_HOME}pids/ccnet.pid ] || kill -USR1 ${cat ${SEAFILE_SERVER_HOME}pids/ccnet.pid}
   endscript
 }
 EOF
@@ -1068,7 +1073,7 @@ cat > ${SEAFILE_SERVER_HOME}/$(basename ${0})_report.log<<EOF
 
   Seafile Data Dir:    ${SEAFILE_DATA_DIR}
 
-  Seafile DB Credentials:  Check /opt/seafile/.my.cnf
+  Seafile DB Credentials:  Check ${SEAFILE_SERVER_HOME}.my.cnf
   Root DB Credentials:     Check /root/.my.cnf
 
   Switch to Seafile system account with: su - ${SEAFILE_USER} -s /bin/bash
@@ -1138,6 +1143,7 @@ does-user-exist-and-abort-if-he-does
 does-directory-exist-abort-if-it-does
 abort-if-seafile-professional-source-is-missing
 update-operating-system
+install-system-utils
 setup-ntpd
 setup-ufw-firewall
 setup-fail2ban
