Added custom installation mode
Start with parameter "custom" to set ports manually

diff --git a/uberspace/seafile-ce_uberspace b/uberspace/seafile-ce_uberspace
--- a/uberspace/seafile-ce_uberspace
+++ b/uberspace/seafile-ce_uberspace
@@ -36,6 +36,8 @@ HOSTNAME=$(hostname -f)
 SEAFILE_ADMIN=admin@${WHOAMI}.${HOSTNAME}
 SEAFILE_USER=seafile
 SERVER_NAME=$(echo ${WHOAMI}$(hostname -s) | cut -c -16)
+# Optionally start installer with parameter "custom" to set ports manually
+MODE=${1}
 
 
 # -------------------------------------------
@@ -108,44 +110,65 @@ done
 
 mysql ${DB_SEAHUB} < ~/seafile/seafile-server-${SEAFILE_VERSION}/seahub/sql/mysql.sql
 
-# -------------------------------------------
-# Get free ports
-# -------------------------------------------
-START_PORT=61100
-END_PORT=65535
-INCREMENT=1
-PORT=${START_PORT}
-PORT_LIST=free_ports.txt
 
-# Empty port list
-echo -n > ${PORT_LIST}
 
-COUNT=1
-while [ ${COUNT} -le 5 ]; do
-  ISFREE=$(netstat -tapln | grep ${PORT})
-    while [[ -n "${ISFREE}" ]]; do
-      PORT=$[PORT+INCREMENT]
-      ISFREE=$(netstat -tapln | grep ${PORT});
-        if [ ${COUNT} > ${END_PORT} ]; then
-          echo "Not enough free ports available. Aborting installation!" ; exit 1
-        fi
+# -------------------------------------------
+# Ports
+# -------------------------------------------
+if [[ ${MODE} = custom ]]
+
+  then
+
+    # -------------------------------------------
+    # Set ports manually
+    # -------------------------------------------
+    read -e -p "Enter Seahub Port:" -i "8000" SEAHUB_PORT
+    read -e -p "Enter Seafdav Port:" -i "8080" SEAFDAV_PORT
+    read -e -p "Enter Fileserver Port:" -i "8082" FILESERVER_PORT
+    read -e -p "Enter CCNET Port:" -i "10001" CCNET_PORT
+    read -e -p "Enter Seafile Server Port:" -i "12001" SEAFILE_PORT
+
+  else
+
+    # -------------------------------------------
+    # Get free ports
+    # -------------------------------------------
+    START_PORT=61100
+    END_PORT=65535
+    INCREMENT=1
+    PORT=${START_PORT}
+    PORT_LIST=free_ports.txt
+
+    # Empty port list
+    echo -n > ${PORT_LIST}
+
+    COUNT=1
+    while [ ${COUNT} -le 5 ]; do
+      ISFREE=$(netstat -tapln | grep ${PORT})
+        while [[ -n "${ISFREE}" ]]; do
+          PORT=$[PORT+INCREMENT]
+          ISFREE=$(netstat -tapln | grep ${PORT});
+            if [ ${COUNT} > ${END_PORT} ]; then
+              echo "Not enough free ports available. Aborting installation!" ; exit 1
+            fi
+        done
+
+    # Write free port to file
+    echo -n "${PORT} " >> ${PORT_LIST}
+
+    # Increment search port
+    PORT=$(( PORT+1 ))
+
+    # Increment loop counter
+    (( COUNT++ ))
     done
 
-# Write free port to file
-echo -n "${PORT} " >> ${PORT_LIST}
+    # Import free ports to vars
+    read SEAHUB_PORT FILESERVER_PORT CCNET_PORT SEAFILE_PORT SEAFDAV_PORT< ${PORT_LIST}
 
-# Increment search port
-PORT=$(( PORT+1 ))
-
-# Increment loop counter
-(( COUNT++ ))
-done
-
-# Import free ports to vars
-read SEAHUB_PORT FILESERVER_PORT SERVER_PORT SEAFILE_SERVER_PORT SEAFDAV_PORT< ${PORT_LIST}
-
-# Delete port list
-rm ${PORT_LIST}
+    # Delete port list
+    rm ${PORT_LIST}
+fi
 
 
 # -------------------------------------------
@@ -209,6 +232,7 @@ runfastcgi(method='threaded', daemonize='false')
 EOF
 
 chmod 755 ~/fcgi-bin/seahub
+
 
 # -------------------------------------------
 # Seafile start script
@@ -279,7 +303,7 @@ SEAFILE_SERVER_SYMLINK=${TOPDIR}/seafile-server-latest
 # -------------------------------------------
 export SEAFILE_LD_LIBRARY_PATH=${INSTALLPATH}/seafile/lib/:${INSTALLPATH}/seafile/lib64:${LD_LIBRARY_PATH}
 LD_LIBRARY_PATH=$SEAFILE_LD_LIBRARY_PATH "${CCNET_INIT}" -c "${DEFAULT_CCNET_CONF_DIR}" \
-  --name "${SERVER_NAME}" --port "${SERVER_PORT}" --host "${HOSTNAME}"
+  --name "${SERVER_NAME}" --port "${CCNET_PORT}" --host "${HOSTNAME}"
 
 # Fix service url
 eval "sed -i 's/^SERVICE_URL.*/SERVICE_URL = https:\/\/${WHOAMI}.${HOSTNAME}/' ${DEFAULT_CCNET_CONF_DIR}/ccnet.conf"
@@ -289,7 +313,7 @@ eval "sed -i 's/^SERVICE_URL.*/SERVICE_URL = https:\/\/${WHOAMI}.${HOSTNAME}/' $
 # Create seafile conf
 # -------------------------------------------
 LD_LIBRARY_PATH=$SEAFILE_LD_LIBRARY_PATH ${SEAF_SERVER_INIT} --seafile-dir "${SEAFILE_DATA_DIR}" \
-  --port ${SEAFILE_SERVER_PORT} --fileserver-port ${FILESERVER_PORT}
+  --port ${SEAFILE_PORT} --fileserver-port ${FILESERVER_PORT}
 
 
 # -------------------------------------------
@@ -472,7 +496,7 @@ cat > ~/seafile/seafile-ce_uberspace.log <<EOF
   SEAHUB_PORT:         $SEAHUB_PORT
   FILESERVER_PORT:     $FILESERVER_PORT
   SERVER_PORT:         $SERVER_PORT
-  SEAFILE_SERVER_PORT: $SEAFILE_SERVER_PORT
+  SEAFILE_PORT:        $SEAFILE_PORT
   SEAFDAV_PORT:        $SEAFDAV_PORT
 
   This report is also saved to ~/seafile/seafile-ce_uberspace.log
@@ -497,6 +521,7 @@ cat > ~/seafile/seafile-ce_uberspace.log <<EOF
 EOF
 
 chmod 600 ~/seafile/seafile-ce_uberspace.log
+
 
 # -------------------------------------------
 # Done!
